### ISSUE TITLE
Taller/thicker timer visualizer 

### ISSUE THREAD

**Issue by ES-Anon** [TechWithTyler/SkippyNums#7]
The current timer visualizer is quite thin, and could be harder to see.  As a user, I would prefer a thicker or more prominent visualization for the timer. (it could remain a bar, or change form)

**Comment by TechWithTyler** [comment]
This isn’t possible with UIProgressView, and if I were to subclass it, the changes made in the subclass wouldn’t reflect in the storyboard so layout issues would not be easy to fix.

**Comment by ES-Anon** [comment]
Closing as "won't do" for now, due to technical implementation issues.
